import 'package:flutter/material.dart';
import './models/category.dart';
import './models/meal.dart';

const DUMMY_CATEGORIES = const [
  Category(
    id: 'c1',
    title: 'Italian',
    color: Colors.purple,
    imageUrl: '',
  ),
  Category(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.red,
    imageUrl: '',
  ),
  Category(
    id: 'c3',
    title: 'Humburgers',
    color: Colors.orange,
    imageUrl: '',
  ),
  Category(
    id: 'c4',
    title: 'Thai Foods ',
    color: Colors.amber,
    imageUrl: '',
  ),
  Category(
    id: 'c5',
    title: 'Light & Lovely',
    color: Colors.blue,
    imageUrl: '',
  ),
  Category(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
    imageUrl: '',
  ),
  Category(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
    imageUrl: '',
  ),
  Category(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
    imageUrl: '',
  ),
  Category(
    id: 'c9',
    title: 'French',
    color: Colors.pink,
    imageUrl: '',
  ),
  Category(
    id: 'c10',
    title: 'Summer',
    color: Colors.teal,
    imageUrl: '',
  ),
];

const DUMMY_MEALS = const [
  Meal(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'Spaghetti with Tomato Sauce',
    imageUrl:
        'https://previews.agefotostock.com/previewimage/medibigoff/8f10bc825d75bcb578b6789e7ae855f1/esy-047375676.webp',
    ingredients: [
      '4 Tomatoes',
      '1 TableSpoon of olive Oil',
      '1 Onion',
      '2 Eggs',
      'Cheese',
    ],
    steps: [
      'steps 1',
      'steps 2',
      'steps 3',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm2',
    categories: [
      'c2',
    ],
    title: 'Shrimp Fried Rice',
    imageUrl:
        'https://s23209.pcdn.co/wp-content/uploads/2017/03/Shrimp-Fried-Rice-Meal-PrepIMG_7687-360x360.jpg',
    ingredients: [
      '1 1/2 cups brown rice',
      '1 pound green beans, trimmed',
      '3 tablespoons reduced sodium soy sauce',
      '1 tablespoon sesame oil',
      '1 tablespoon freshly grated ginger',
      '1/4 teaspoon white pepper, optional',
      '2 tablespoons olive oil',
      '1 1/2 pounds medium shrimp, peeled and deveined',
      'Kosher salt and freshly ground black pepper, to taste',
      '2 cloves garlic, minced',
      '1 onion, diced',
      '2 carrots, peeled and grated',
      '1/2 cup corn, frozen, canned or roasted',
      '1/2 cup frozen peas',
      '2 green onions, thinly sliced',
    ],
    steps: [
      'In a large saucepan of 3 cups water, cook rice according to package instructions; set aside.',
      'In a large pot of boiling salted water, blanch green beans until bright green in color, about 2 minutes. Drain well and cool in a bowl of ice water. Drain well and set aside.',
      'In a small bowl, whisk together soy sauce, sesame oil, ginger and white pepper, if using; set aside.',
      'Heat olive oil in a large skillet or wok over medium high heat. Add shrimp, and cook, stirring occasionally, until pink, about 2-3 minutes; season with salt and pepper, to taste; set aside.',
      'Add garlic and onion to the skillet, and cook, stirring often, until onions have become translucent, about 3-4 minutes.',
      'Stir in carrots, corn and peas. Cook, stirring constantly, until vegetables are tender, about 3-4 minutes.',
      'Stir in rice, green onions and soy sauce mixture. Cook, stirring constantly, until heated through, about 2 minutes. Stir in shrimp.',
      'Place rice mixture and green beans into meal prep containers.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm3',
    categories: [
      'c4',
    ],
    title: 'Thai Healthy Chiken Pad',
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2014/10/DSC_0102-3.jpg',
    ingredients: [
      '18oz raw chicken breasts',
      '4oz (56g) flat brown rice noodles',
      '3 tbsp garlic paste',
      'Veggies :',
      '     - 1 red bell pepper',
      '     - 1 cup mushrooms (chopped)',
      '     - 1.5 cup bean sprouts',
      '     - 1 cup green onions (chopped)',
      '     - fresh cilantro',
      'Sauce :',
      '     - 1/4 cup rice vinegar (or fish sauce)',
      '     - 1/8 cup Coconut Aminos (low sodium soy sauce)',
      '     - 1/8 cup Red chili pepper sauce',
      '     - 2 tbsp coconut sugar',
      '     - juice from 1 lime',
    ],
    steps: [
      'Boil brown rice noodles. Drain and set aside.',
      'Chop up veggies – bell pepper, mushrooms, green onions, limes, cilantro.',
      'Slice chicken breast into small pieces.',
      'In a bowl, mix rice vinegar or fish sauce, coconut sugar, red chili pepper sauce, & fresh lime juice.',
      'Spray a nonstick skillet with coconut oil, then add garlic paste. Toss in chicken breast pieces and cook.',
      'Finally, add noodles, then fresh veggies and the sauce.',
      'Build your meals.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: true,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm4',
    categories: [
      'c4',
    ],
    title: 'Sweet Thai Curry Salmon Kebabs',
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2019/04/red-curry-salmon-kebabs-3-1024x768.jpg',
    ingredients: [
      'Marinade :',
      '     - 2 1/2 tablespoons red curry paste',
      '     - 1 tablespoon coconut sugar (SUBSTITUTE: brown sugar; agave)',
      '     - 1 tablespoon avocado oil or olive oil',
      '     - 2 teaspoons ginger',
      '     - juice from 1/2 lime',
      '24oz (1 1/2 lb) raw salmon chunks, skin removed',
      '1 large (red) onion, sliced into chunks for kebab',
      '2 medium zucchinis, sliced into discs',
      '1 large bell pepper (any color)',
    ],
    steps: [
      'Set oven to 420F.',
      'If needed, slice skin from center-cut salmon and chop into large chunks.',
      'Add the ingredients for the marinade into a bowl, stir, then gently fold in salmon chunks. let it marinate for at least 30 minutes.',
      'Once marinated, build the kebabs.',
      'Set a nonstick skillet on medium high heat.  Once the skillet is very hot, spray it with a little oil, then add the kebabs.',
      'Sear on all 4 sides until the outside is crispy, then place them on a baking sheet lined with parchment paper (or baking rack).  Bake for  12 – 15 minutes.',
    ],
    duration: 25,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: true,
    isVegetarian: true,
  ),
  Meal(
    id: 'm5',
    categories: [
      'c5',
      'c4',
    ],
    title: 'Thai Salmon & Veggies In Coconut Curry',
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2019/07/salmon-coconut-curry-1.jpg',
    ingredients: [
      '1 1/4 lb salmon fillets, skinned and cut into large chunks',
      'pinch of sea salt & pepper',
      '2 teaspoons coconut sugar',
      'spray avocado or coconut oil',
      '1 tablespoon avocado or coconut oil',
      '1 tablespoon fresh garlic, minced',
      '1/2 cup diced onion',
      '1 1/2 tablespoons fresh ginger',
      '2 teaspoons lime zest',
      '2 cups sugar snap peas',
      '1 (red) bell pepper, cut into strips',
      '1 can (13.5oz) full fat coconut milk',
      '2/3 cup seafood stock (or chicken or veggie broth)',
      '1/4 cup yellow (or green or red) curry paste',
      '1 teaspoon turmeric',
      '12oz (340g) cauliflower florets',
      'Garnish :',
      '     - basil',
      '     - fresh lime',
    ],
    steps: [
      'Season salmon with sea salt, pepper and coconut sugar. Rub it all over the skinless, raw salmon chunks.',
      'Set skillet on medium high heat and once hot, spray with oil.  Add the salmon fillets and sear for no more than 2 minutes to add color to the outside of the salmon, then remove the salmon from the skillet.',
      'Add oil to the skillet, then add garlic, onion, ginger and lime zest.  Caramelize the onions and season the oil, about 3 minutes.',
      'Once caramelized, increase heat to high then add sugar snap peas and bell pepper.  Sear the veggies for 2 – 3 additional minutes.',
      'Add coconut milk, broth, curry paste and turmeric.  Reduce heat and bring to a light simmer.   Add the cauliflower  florets, then cover and cook for 8 to 10 minutes to  soften the cauliflower.',
      'After 10 minutes, remove the skillet from the heat and add the salmon  chunks back to the skillet and allow them salmon to finish cooking in the sauce.  Garnish with (Thai) basil and fresh lime.',
      'Enjoy as-is or with brown rice or jasmine rice for a heartier meal!',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm6',
    categories: [
      'c6',
      'c4',
    ],
    title: 'Hi-Protein Thai Almond Chicken Summer Salad',
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2015/06/IMG_3216-3.jpg',
    ingredients: [
      '1.5 lb raw chicken breasts',
      'Salad :',
      '     - 5 cups (425g) broccoli slaw (mixture of broccoli, cabbage and carrots)',
      '     - 2 clusters baby bok choy',
      '     - 1/3 cup chopped mint',
      'Almond Sauce :',
      '     - 5 tablespoons raw almond butter (no salt added, best to purchase the kind with oil in it)',
      '     - 3 tablespoons Bragg Liquid Aminos (or coconut aminos or low sodium soy sauce)',
      '     - 2 tablespoons rice vinegar',
      '     - juice from 1/2 lime (or whole lime if an extra tangy flavor is desired)',
      '     - 1 tablespoon raw organic honey',
      '     - pinches of red pepper flakes (as needed or desired for heat)',
      '     - tablespoons of water if needed to make the sauce thinner',
      'Garnish :',
      '     - shaved almonds',
      '     - cilantro',
      '     - red chile pepper',
    ],
    steps: [
      'Spray a nonstick skillet with coconut oil and set on medium heat. Toss in the chicken breasts without seasoning since the flavor will come from the salad and the almond dressing.  Once the chicken breasts are completely cooked, set them aside and allow them to cool down a bit.',
      'Combine all the ingredients for the almond sauce together in a bowl and whisk together. Add a few tablespoons of water, if needed in order to make the sauce thinner.',
      'Chop up the chicken breasts, bok chot and mint.',
      'In a large bowl, add the ingredients for the salad plus the (cooled and cooked) chopped chicken breasts.  Mix together.',
      'Divide the salad mixture into four equal servings.  For each serving add one-fourth of the almond sauce. **TIP: if this is for meal prep or to be eaten later, only add the sauce to the salad when you are going to eat it.**',
      'Garnish with cilantro, shaved almonds and sliced red chile peppers.',
      'Enjoy!',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm7',
    categories: [
      'c3',
      'c7',
    ],
    title: 'Chipotle Walnut & Vegan Black Bean Burger',
    imageUrl:
        'https://369t7u43n93dgc5pt43uc681-wpengine.netdna-ssl.com/wp-content/uploads/2018/06/walnut-bean-burger-4.jpg',
    ingredients: [
      'Ingredients for 4 hearty patties :',
      '     - 2 tablespoons milled flax (mixed with 3 tablespoons water)',
      '     - 1 tablespoon minced garlic',
      '     - 1/2 cup onion (red or white)',
      '     - 1/2 cup (~56g) raw walnuts',
      '     - 1 can (15oz) no-salt added black beans, rinsed and drained',
      '     - 3 chipotle peppers with 1 tablespoon adobo sauce',
      '     - 1/3 cup  cilantro',
      '     - 1/2 cup raw oats',
      '     - sea salt & pepper to taste',
    ],
    steps: [
      'Mix together the milled flax and water and set aside.',
      'Set a nonstick skillet on medium heat.  Once it’s hot, spray with olive oil then add garlic and onion.  Caramelize for 3 to 5 minutes, or until golden brown and somewhat translucent, and be careful not to burn the garlic.',
      'Add the onions to a food processor, along with raw walnuts.  Blend for about 1 minute until minced.',
      'Then add only HALF of the black beans and then the remaining ingredients – except for the flax egg and oat. Blend for 1 to 2 minutes until well combined.',
      'Lightly mash the remaining black beans together in a bowl using a fork to create some texture for the burger.  Then add the bean mixture, flax egg and raw oats.   Mix everything together well, then season to taste with sea salt & pepper.  Cover the bowl with plastic wrap then place in the fridge for 20 minutes.',
      '     - Batter too wet?  add tablespoons of raw oats',
      '     - Batter too “crumbly”?  Add another flax egg (1 tablespoon milled flax set in 1.5 tablespoon water)',
      'Form four equal sized patties, then place the patties in the freezer for 20 minutes to set.  This will help them retain their form when cooking.',
      'Set a nonstick skillet on medium heat and once hot, generously spray with olive oil.  Add the patties and cook for 6 to 8 minutes on each side, or until the outside edges of the patty turn brown and slightly crispy.',
      'Enjoy the patty with a fresh salad or as a delicious postworkout hamburger.',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm8',
    categories: [
      'c8',
    ],
    title: '8 Spaghetti with Tomato Sauce',
    imageUrl:
        'https://media-cdn.tripadvisor.com/media/photo-s/12/44/81/81/kfc-chicken-wings-with.jpg',
    ingredients: [
      '4 Tomatoes',
      '1 TableSpoon of olive Oil',
      '1 Onion',
    ],
    steps: [
      'steps 1',
      'steps 2',
      'steps 3',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm9',
    categories: [
      'c9',
    ],
    title: '9 Spaghetti with Tomato Sauce',
    imageUrl:
        'https://media-cdn.tripadvisor.com/media/photo-s/12/44/81/81/kfc-chicken-wings-with.jpg',
    ingredients: [
      '4 Tomatoes',
      '1 TableSpoon of olive Oil',
      '1 Onion',
    ],
    steps: [
      'steps 1',
      'steps 2',
      'steps 3',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  ),
  Meal(
    id: 'm10',
    categories: [
      'c10',
    ],
    title: '10 Spaghetti with Tomato Sauce',
    imageUrl:
        'https://media-cdn.tripadvisor.com/media/photo-s/12/44/81/81/kfc-chicken-wings-with.jpg',
    ingredients: [
      '4 Tomatoes',
      '1 TableSpoon of olive Oil',
      '1 Onion',
    ],
    steps: [
      'steps 1',
      'steps 2',
      'steps 3',
    ],
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
    isGlutenFree: false,
    isLactoseFree: false,
    isVegan: false,
    isVegetarian: false,
  )
];
